import React from "react";

const API_DATA=[
    {id:'1',
        title:"DNK Yellow Shoes",
        image:'https://i.postimg.cc/1twGh5Ds/sports-shoe3-300x300.jpg',
        images:['https://i.postimg.cc/1twGh5Ds/sports-shoe3-300x300.jpg'],
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'450', 
        special:true,
        color:[]
    },
    {id:'2',
        title:"DNK Blue Shoes",
        image:'https://i.postimg.cc/1twGh5Ds/sports-shoe3-300x300.jpg',
        images:['https://i.postimg.cc/j2LCxKbG/sports-shoe1-600x600.jpg','https://i.postimg.cc/QCJsZyBR/sports-shoe2.jpg','https://i.postimg.cc/hj4fYT34/sports-shoe4-600x600.jpg','https://i.postimg.cc/NMN5vFW6/sports-shoe5-600x600.jpg'],
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'450', 
        special:true,
        color:["red","green","yellow"]
    },
    {id:'3',
        title:"Dark Brown Jeans",
        image:'https://i.postimg.cc/X78gYJmv/product-m-jeans1-300x300.jpg',
        images:['https://i.postimg.cc/X78gYJmv/product-m-jeans1-300x300.jpg'],
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'450', 
        special:true,
        color:[]
    },
    {id:'4',
        title:"Blue Denim Jeans",
        image:'https://i.postimg.cc/sgH95LVd/product-w-jeans2-300x300.jpg',
        images:['https://i.postimg.cc/sgH95LVd/product-w-jeans2-300x300.jpg'],
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'450', 
        special:true,
        color:[]
    },
    {id:'5',
        title:"Basic Gray Jeans",
        image:'https://i.postimg.cc/MGc05YTc/product-w-jeans4-300x300.jpg',
        images:['https://i.postimg.cc/MGc05YTc/product-w-jeans4-300x300.jpg'],
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'450', 
        special:true,
        color:[]
    },
    {id:'6',
        title:"Blue Denim Shorts",
        image:'https://i.postimg.cc/YCCzG7Bz/product-w-jeans1-300x300.jpg',
        images:['https://i.postimg.cc/YCCzG7Bz/product-w-jeans1-300x300.jpg'],
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'450', 
        special:true,
        color:[]
    },
    {id:'7',
        title:"Anchor Bracelet",
        image:'https://i.postimg.cc/wxDVnFkL/product-accessory2-300x300.jpg',
        images:['https://i.postimg.cc/wxDVnFkL/product-accessory2-300x300.jpg'],
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'450', 
        special:true,
        color:["red","green","yellow"]
    },
    {id:'8',
        title:"Bocho Bangle Bracelet",
        image:'https://i.postimg.cc/1X1KfNy8/product-accessory1-300x300.jpg',
        images:['https://i.postimg.cc/1X1KfNy8/product-accessory1-300x300.jpg'],
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'450', 
        special:true,
        color:["red","green","yellow"]
    },
    {id:'8',
        title:"Light Brown Purse",
        image:'https://i.postimg.cc/rFcJTWhb/product-bag1-300x300.jpg',
        images:['https://i.postimg.cc/rFcJTWhb/product-bag1-300x300.jpg'],
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'450', 
        special:true,
        color:[]
    },
    {id:'9',
        title:"Bright Red Bag",
        image:'https://i.postimg.cc/XqKkF7vQ/product-bag3-300x300.jpg',
        images:['https://i.postimg.cc/XqKkF7vQ/product-bag3-300x300.jpg'],
        category:'women',
        description: 'Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit sed.',
        price:'450', 
        special:true,
        color:["red","green","yellow"]
    },
]
export default API_DATA